development:
  clients:
    default:
      database: mongoid_activeadmin_development
      hosts:
        - localhost:27017
  options:

test:
  clients:
    default:
      database: mongoid_activeadmin_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
